#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## transfer.py
## File description:
## transfer.py
##

#!/usr/bin/python3.7
import sys
import math
from math import*

try:
    sys.exit(84)
except:
    sys.exit(84)
